services:
  postgres_sm_test:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=statemachine_test
    ports:
      - '5432:5432'
    volumes:
      - "./postgres_14/postgres.conf:/usr/local/etc/postgres/postgres.conf"
      - "./postgres_14/data:/var/lib/postgresql/data:delegated"
    command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"